syntax = "proto3";

package ON.Fragments.Content.Video.Rumble;
import "Protos/ON/Fragments/Content/Video/Rumble/RumbleLivestreamRecord.proto";

service RumbleLivestreamInterface {
	rpc GetLivestream(RumbleLivestreamRequest) returns (RumbleLivestreamResponse);
	rpc MutateRumbleLivestreamChannelUrl(MutateRumbleLivestreamChannelUrlRequest) returns (MutateRumbleLivestreamChannelUrlResponse);
	rpc RemoveRumbleLivestreamChannelUrl(RumbleLivestreamChannelUrlRequest) returns (MutateRumbleLivestreamChannelUrlResponse);
	rpc GetRumbleLivestreamChannelUrl(RumbleLivestreamChannelUrlRequest) returns (GetRumbleLivestreamChannelUrlResponse);
	rpc ListRumbleLivestreamChannelUrls(ListRumbleLivestreamChannelUrlsRequest) returns (ListRumbleLivestreamChannelUrlsResponse);
}

message RumbleLivestreamRequest {
	string ChannelId = 1;
	uint32 MaxNumResults = 2;
}

message RumbleLivestreamResponse {
	uint32 Now = 1;
	string Type = 2;
	string UserId = 3;
	string ChannelId = 4;
	string Since = 5;
	uint32 MaxNumResults = 6;
	RumbleLivestreamFollowerData Followers = 7;
	RumbleLivestreamSubscriberData Subscribers = 8;
	repeated RumbleLivestreamRantRecord Livestreams = 9;
}

message MutateRumbleLivestreamChannelUrlRequest {
	RumbleLivestreamChannelRecord Channel = 1;
}

message RumbleLivestreamChannelUrlRequest {
	string ChannelId = 1;
}

message MutateRumbleLivestreamChannelUrlResponse {
	bool IsSuccess = 1;
	string Error = 2;
}

message GetRumbleLivestreamChannelUrlResponse {
	RumbleLivestreamChannelRecord Channel = 1;
}

message ListRumbleLivestreamChannelUrlsRequest {}

message ListRumbleLivestreamChannelUrlsResponse {
	repeated RumbleLivestreamChannelRecord Channels = 1;
}