syntax = "proto3";

import "google/api/annotations.proto";
package ON.Fragments.Content.Video.Rumble;
import "Protos/ON/Fragments/Content/Video/Rumble/RumbleLivestreamRecord.proto";

service RumbleLivestreamInterface {
    rpc GetLivestream(RumbleLivestreamRequest) returns (RumbleLivestreamResponse) {
        option (google.api.http) = {
            get: "/api/video/rumble/livestream/{ChannelId}"
        };
    }
    rpc MutateRumbleLivestreamChannelUrl(MutateRumbleLivestreamChannelUrlRequest) returns (MutateRumbleLivestreamChannelUrlResponse) {
        option (google.api.http) = {
            post: "/api/admin/video/rumble/livestream/{Channel.ChannelId}/url";
            body: "*"
        };
    }
    rpc RemoveRumbleLivestreamChannelUrl(RumbleLivestreamChannelUrlRequest) returns (MutateRumbleLivestreamChannelUrlResponse) {
        option (google.api.http) = {
            delete: "/api/admin/video/rumble/livestream/{ChannelId}/url"
        };
    }
    rpc GetRumbleLivestreamChannelUrl(RumbleLivestreamChannelUrlRequest) returns (GetRumbleLivestreamChannelUrlResponse) {
        option (google.api.http) = {
            get: "/api/admin/video/rumble/livestream/{ChannelId}/url"
        };
    }
    rpc ListRumbleLivestreamChannelUrls(ListRumbleLivestreamChannelUrlsRequest) returns (ListRumbleLivestreamChannelUrlsResponse) {
        option (google.api.http) = {
            get: "/api/admin/video/rumble/livestream/urls"
        };
    }
}


message RumbleLivestreamRequest {
	string ChannelId = 1;
	uint32 MaxNumResults = 2;
}

message RumbleLivestreamResponse {
	uint32 Now = 1;
	string Type = 2;
	string UserId = 3;
	string ChannelId = 4;
	string Since = 5;
	uint32 MaxNumResults = 6;
	RumbleLivestreamFollowerData Followers = 7;
	RumbleLivestreamSubscriberData Subscribers = 8;
	repeated RumbleLivestreamRantRecord Livestreams = 9;
}

message MutateRumbleLivestreamChannelUrlRequest {
	RumbleLivestreamChannelRecord Channel = 1;
}

message RumbleLivestreamChannelUrlRequest {
	string ChannelId = 1;
}

message MutateRumbleLivestreamChannelUrlResponse {
	bool IsSuccess = 1;
	string Error = 2;
}

message GetRumbleLivestreamChannelUrlResponse {
	RumbleLivestreamChannelRecord Channel = 1;
}

message ListRumbleLivestreamChannelUrlsRequest {}

message ListRumbleLivestreamChannelUrlsResponse {
	repeated RumbleLivestreamChannelRecord Channels = 1;
}