syntax = "proto3";

package ON.Fragments.Content.Video.Rumble;
import "Protos/ON/Fragments/Content/Video/Rumble/RumbleLivestreamRecord.proto";

service RumbleLivestreamInterface {
	rpc GetLivestream(RumbleLivestreamRequest) returns (RumbleLivestreamResponse);
	rpc AddRumbleLivestreamChannelUrl(AddRumbleLivestreamChannelUrlRequest) returns (AddRumbleLivestreamChannelUrlResponse);
	rpc EditRumbleLivestreamChannelUrl(EditRumbleLivestreamChannelUrlRequest) returns (EditRumbleLivestreamChannelUrlResponse);
	rpc RemoveRumbleLivestreamChannelUrl(RemoveRumbleLivestreamChannelUrlRequest) returns (RemoveRumbleLivestreamChannelUrlResponse);
	rpc GetRumbleLivestreamChannelUrl(GetRumbleLivestreamChannelUrlRequest) returns (GetRumbleLivestreamChannelUrlResponse);
	rpc ListRumbleLivestreamChannelUrls(ListRumbleLivestreamChannelUrlsRequest) returns (ListRumbleLivestreamChannelUrlsResponse);
}

message RumbleLivestreamRequest {
	string ChannelId = 1;
	uint32 MaxNumResults = 2;
}

message RumbleLivestreamResponse {
	uint32 Now = 1;
	string Type = 2;
	string UserId = 3;
	string ChannelId = 4;
	string Since = 5;
	uint32 MaxNumResults = 6;
	RumbleLivestreamFollowerData Followers = 7;
	RumbleLivestreamSubscriberData Subscribers = 8;
	repeated RumbleLivestreamRantRecord Livestreams = 9;
}

message AddRumbleLivestreamChannelUrlRequest {
	RumbleLivestreamChannelRecord Channel = 1;
}

message AddRumbleLivestreamChannelUrlResponse {
	bool IsSuccess = 1;
	string Error = 2;
}

message EditRumbleLivestreamChannelUrlRequest {
	RumbleLivestreamChannelRecord Channel = 1;
}

message EditRumbleLivestreamChannelUrlResponse {
	bool IsSuccess = 1;
	string Error = 2;
}

message RemoveRumbleLivestreamChannelUrlRequest {
	string ChannelId = 1;
}

message RemoveRumbleLivestreamChannelUrlResponse {
	bool IsSuccess = 1;
	string Error = 2;
}

message GetRumbleLivestreamChannelUrlRequest {
	string ChannelId = 1;
}

message GetRumbleLivestreamChannelUrlResponse {
	RumbleLivestreamChannelRecord Channel = 1;
}

message ListRumbleLivestreamChannelUrlsRequest {}

message ListRumbleLivestreamChannelUrlsResponse {
	repeated RumbleLivestreamChannelRecord Channels = 1;
}